using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LRWEB_V1_CLIENT_SIDE_T24.Areas.LRForms.Models
{
    public class _CLIENT_INFO
    {
        public string salutation { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string suffix { get; set; }
        public string birthPlace { get; set; }
        public string birthDate { get; set; }
        public string age { get; set; }
        public string gender { get; set; }
        public string religion { get; set; }
        public string citizenship { get; set; }
        public string civilStatus { get; set; }
        public string civilStatusID { get; set; }
        public string TIN { get; set; }
        public string mothersMaidenName { get; set; }
        public string SSS { get; set; }
        public string GSIS { get; set; }
        public string spouseSalutation { get; set; }
        public string spouseFirstname { get; set; }
        public string spouseMiddlename { get; set; }
        public string spouseLastname { get; set; }
        public string spouseSuffix { get; set; }
        public string spouseGender { get; set; }
        public string spouseBirthDate { get; set; }
        public string spouseAge { get; set; }
        public string dependents { get; set; }
        public string spouseEmployer { get; set; }
        public string spouseOccupation { get; set; }
        public string spouseMonthlyIncome { get; set; }
        public string spouseNumber { get; set; }
        public string Present_Address { get; set; }
        public string Present_Province { get; set; }
        public string Present_ProvinceID { get; set; }
        public string Present_City { get; set; }
        public string Present_CityID { get; set; }
        public string Present_Barangay { get; set; }
        public string Present_BarangayID { get; set; }
        public string Present_Country { get; set; }
        public string Present_Zipcode { get; set; }
        public string Present_Ownership { get; set; }
        public string Present_OwnershipID { get; set; }
        public string Present_Years { get; set; }
        public string Present_Months { get; set; }
        public string Present_LengthOfStay { get; set; }
        public string Present_Telephone { get; set; }
        public string Permanent_Address { get; set; }
        public string Permanent_Province { get; set; }
        public string Permanent_ProvinceID { get; set; }
        public string Permanent_City { get; set; }
        public string Permanent_CityID { get; set; }
        public string Permanent_Barangay { get; set; }
        public string Permanent_BarangayID { get; set; }
        public string Permanent_Country { get; set; }
        public string Permanent_Zipcode { get; set; }
        public string Permanent_Ownership { get; set; }
        public string Permanent_OwnershipID { get; set; }
        public string Permanent_Years { get; set; }
        public string Permanent_Months { get; set; }
        public string Permanent_LengthOfStay { get; set; }
        public string Permanent_Telephone { get; set; }
        public string dateHired { get; set; }
        public string tenure { get; set; }
        public string employeeNumber { get; set; }
        public string rank { get; set; }
        public string department { get; set; }
        public string monthlyAllowance { get; set; }
        public string occupation { get; set; }
        public string natureOfWork { get; set; }
        public string natureOfWorkID { get; set; }
        public string sourceOfIncomeOthers { get; set; }
        public string monthlyIncomeOthers { get; set; }
        public string Employer_Address { get; set; }
        public string Employer_Province { get; set; }
        public string Employer_ProvinceID { get; set; }
        public string Employer_City { get; set; }
        public string Employer_CityID { get; set; }
        public string Employer_Barangay { get; set; }
        public string Employer_BarangayID { get; set; }
        public string Employer_Country { get; set; }
        public string Employer_Zipcode { get; set; }
        public string Employer_Telephone { get; set; }
        public string employee_reference { get; set; }
        public string CIFno { get; set; }
        public string application_number { get; set; }
        public string referenceNumber { get; set; }
        public string netIncome { get; set; }
        public string netPay { get; set; }
        public string otherLoans { get; set; }
        public string loanAmount { get; set; }
        public string loanTerms { get; set; }
        public string loanPurpose { get; set; }
        public string loanPurposeID { get; set; }
        public string loanPurposeOthers { get; set; }
        public string groupCode { get; set; }
        public string creditOption { get; set; }
        public string creditOptionID { get; set; }
        public string nameToDisplay { get; set; }
        public string accountNumber { get; set; }
        public string bankName { get; set; }
        public string attachment1 { get; set; }
        public string attachment2 { get; set; }
        public string attachment3 { get; set; }
        public string attachment4 { get; set; }
        public string attachment5 { get; set; }
        public string attachment6 { get; set; }
        public string attachment7 { get; set; }
        public string attachment8 { get; set; }
        public string attachment9 { get; set; }
        public string legalID { get; set; }
        public string nameOnID { get; set; }
        public string documentName { get; set; }
        public string documentNameID { get; set; }
        public string issueAuth { get; set; }
        public string issueAuthID { get; set; }
        public string issueDate { get; set; }
        public string expirationDate { get; set; }
        public string finacle_sol_id { get; set; }
        public string sol_id { get; set; }
    }
}